---
platform:
  os: linux
  arch: amd64

# Begin
clone:
  git-clone:
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD
    image: "casperlabs/clarity-build:latest"

kind: pipeline
type: docker
name: build-test-publish

steps:
- name: install-dependencies
  commands:
  - npm install
  image: "casperlabs/clarity-build:latest"

- name: run-build
  commands:
  - npm run build
  image: "casperlabs/clarity-build:latest"
  depends_on:
  - install-dependencies

- name: run-test
  commands:
  - npm run test_ci
  image: "casperlabs/clarity-build:latest"
  depends_on:
  - run-build

- name: run-complete
  commands:
  - npm run complete
  image: "casperlabs/clarity-build:latest"
  depends_on:
  - run-test
  when:
    event:
    - push
    branch:
    - master

- name: upload-extension
  image: "casperlabs/clarity-build:latest"
  commands:
  - "./publish.sh"
  environment:
    APPLICATION_ID:
      from_secret: plugin_application
    CLIENT_ID:
      from_secret: plugin_client_id
    CLIENT_SECRET:
      from_secret: plugin_client_secret
    REFRESH_TOKEN:
      from_secret: plugin_refresh_token
  depends_on:
  - run-complete
  when:
    event:
    - push
    branch:
    - master

trigger:
  branch:
  - master
  - trying
  - staging

---
kind: pipeline
type: docker
name: failed-build-alert

clone:
  disable: true

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    template:
    - |
      signer-repo build status: *{{ uppercasefirst build.status }}*
      Author: {{ build.author }}
      Drone Build: <{{ build.link }}|#{{ build.number }}>
      Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
trigger:
  status:
  - failure
  branch:
  - master
  - trying
  - staging

depends_on:
- build-test-publish
